### ISSUE TITLE
command 'drive' not found

### ISSUE THREAD

**Issue by Loiseau2nuit** [rakyll/drive#60]
Hi there!

For a reason I can't figure out, the command 'drive' is still not working (command nort found) even after "go get github.com/rakyll/drive" (seems to) have been running succesfully ?

Someone please, can help me with this ? Thanks in advance :)

**Comment by odeke-em** [comment]
You'll need to add your gopath and the binaries path to your .bashrc or .bash_profile depending on if you are on Linux or MacOSX, with something like this:

``` shell
$ cat << ! >> ~/.bashrc
> export GOPATH=\$HOME/go
> export PATH=\$GOPATH:\$GOPATH/bin:\$PATH
> !
```

If your problem persists please open it up on https://github.com/odeke-em/drive since as mentioned in the README, drive moved there.

**Comment by Walkman100** [comment]
> even after "go get github.com/rakyll/drive"

Pretty sure it's supposed to be `go get -u github.com/rakyll/drive/cmd/drive`

**Comment by LoLei** [comment]
You need to use the new repository at https://github.com/odeke-em/drive.

Then `go get github.com/odeke-em/drive/drive-gen && drive-gen`. Also if you use GVM, be sure to start golang again if it ended after the installation with `gvm use go1.4`.

You also need at least go version 1.4 (I think).

I realize this issue is old, just for future reference.

**Comment by rakyll** [comment]
Closing the issue, please use the maintained fork.
